const ExcelJS = require('exceljs');

const english = {
    "popular_brand": "Popular Brands",
    "view_more": "View more",
    'view_less': "View less",
    "categories": "Categories",
    "coming_soon": "Coming soon",
    "search_component": "Search component",
    "continue": "Continue",
    "submit": "Submit",
    "cancel": "Cancel",
    "ok": "Ok",
    "done": "Done",
    "remove": "Remove",
    "add_to_cart": "Add To Cart",
    "discard": "Discard",
    "news": "News",
    "reference": "Reference",
    "product_detail": "Product detail",
    "buy_now": "Buy now",
    "tech_specs": "Tech Specs",
    "related_product": "Related product",
    "search_product": "Search Products",
    "browse_categories": "Browse categories",
    "recent_search": "Recent Search",
    "category": "Category",
    "recommended_for_you": "Recommended for you",
    "search_brand": "Search brand...",
    "search_categories": "Search categories...",
    "brand": "Brand",
    "search": "Search...",
    "information": "Information",
    "faq": "FAQ",
    "loading": "Loading",
    "end_of_records": "End Of Records",
    "content": "Content",
    "delete": "Delete",
    "do_you_want_to_remove": "Do you want to remove",
    "do_you_want_to_delete": "Do you want to delete",
    "please_enter_phone_number": "Please enter phone number",
    "please_enter_address": "Please enter address",
    "info": "Info",
    "empty": "No Records",
    "no_review": "No reviews",
    "searching": "Searching",
    "please_input_qty": "Please input quantity",
    "buy_again": "Buy again",
    "order_history_info": "Order history info",
    "do_you_want_clear_search_history": "Do you want to clear search histories",
    "are_you_sure_want_to_sign_out": "Are you sure want to sign out",
    "signing_out": "Signing out",
    "added_to_cart": "Added to cart",
    "please_select_payment_method": "Please select payment method",
    "enter_six_digit_code": "Please enter 6 digit code",
    "document_no": "Document no",
    "phone_no": "Phone number",
    "phone": "Phone",
    "delivery_fee": "Delivery fee",
    "delivery_info": "Delivery info",
    "order_items_info": "Order items info",
    "order_status": "Order status",
    "please_select_image": "Please select images",
    "problem_image": "Problem image",
    "map_service_not_available": "Map service not available",
    "update": "Update",
    "create": "Create",
    "not_available": "Not available",
    "riel": "Riel",
    "usd": "USD",
    "log_to_your_account": "Login to your account",
    "forgot_password": "Forgot password",
    "enter_your_phone_number": "Enter your phone number",
    "already_has_account": "Already has account",
    "register": "Register",
    "login": "Login",
    "sign_up": "Sign up",
    "sign_in": "Sign in",
    "do_not_have_account": "Don't have an account",
    "not_receive_code": "Not receive code",
    "password": "Password",
    "resend": "Resend",
    "create_account": "Create account",
    "agree_term_and_service":
        "By signing up you agree to our terms and conditions.",
    "enter_validation_code": "Enter validation code",
    "please_enter_6_digit_code": "Please enter 6 digit code",
    "please_enter_first_name": "Please enter first name",
    "please_enter_last_name": "Please enter last name",
    "please_enter_your_name": "Please enter your name",
    "please_enter_password": "Please enter password",
    "please_enter_confirm_password": "Please enter confirm password",
    "please_check_term_and_condition": "Please check term and condition",
    "processing": "Processing",
    "discount_amount": "Discount amount",
    "tax": "Tax",
    "next": "Next",
    "please_select_delivery_method": "Please select delivery method",
    "pick_up": "Pick Up",
    "check_out": "Check Out",
    "pay_now": "Pay Now",
    "contact_seller": "Contact seller",
    "delivery_to": "Delivery to",
    "payment_method": "Payment Method",
    "summary": "Summary",
    "color": "Color",
    "quantity": "Quantity",
    "cash": "Cash",
    "card": "Card",
    "tap_to_select_payment": "Tab to select payment",
    "select_category": "Select Category",
    "select_cpu": "Select CPU",
    "select_group": "Select Group",
    "select_ram": "Select Ram",
    "select_storage": "Select Storage",
    "place": "Place Name",
    "home_no": "Home no",
    "street_no": "Street no",
    "location": "Location",
    "request_delivery": "Request Delivery",
    "time": "Time",
    "request_service": "Service Request",
    "delivery": "Delivery",
    "request": "Request",
    "problem_description": "Problem description",
    "type": "Type",
    "request_new_service": "Request New Service",
    "pending": "Pending",
    "edit": "Edit",
    "result": "Result",
    "checking": "Checking",
    "problem": "Problem",
    "complete": "Complete",
    "get": "Get",
    "review": "Review",
    "how_would_you_like_rate_this_product":
        "How would you like to rate this product",
    "write_your_option": "Write your option",
    "do_you_have_any_photos": "Do you have any photos",
    "add_photo": "Add photo",
    "gallery": "Gallery",
    "camera": "Camera",
    "processor": "Processor",
    "memory": "Memory",
    "storage": "Storage",
    "display": "Display",
    "graphic": "Graphic",
    "os": "OS",
    "code": "Code",
    "notification": "Notification",
    "shop": "Shop",
    "chat": "Chat",
    "type_your_message": "Type your message",
    "discount": "Discount",
    "home": "Home",
    "cart": "Cart",
    "menu": "Menu",
    "build_computer": "Build computer",
    "compare": "Compare",
    "wish_list": "WishList",
    "blog": "Blog",
    "jobs": "Jobs",
    "about_us": "About us",
    "contact_us": "Contact us",
    "more": "More",
    "language": "Language",
    "tracking_service": "Tracking service",
    "order_history": "Order history",
    "corporate": "Corporate",
    "black_list": "Blacklist",
    "e_brochure": "E-brochure",
    "leasing": "Leasing",
    "service": "Service",
    "networking": "Networking",
    "change_password": "Change password",
    "sign_out": "Sign out",
    "add_delivery": "Add Delivery",
    "address": "Address",
    "address_2": "Address 2",
    "add_new_address": "Add New Address",
    "please_select_delivery_address": "Please select delivery address",
    "choose_spec_that_you_want": "Choose spec that you want",
    "mother_board": "Motherboard",
    "cpu": "CPU",
    "cpu_cooling": "CPU Fan",
    "ram": "RAM",
    "hard_disk": "Hard Disk",
    "ssd": "SSD",
    "graphic_card": "Graphic card",
    "case": "Case",
    "power_supply": "Power supply",
    "case_fan": "Case fan",
    "monitor": "Monitor",
    "mouse": "Mouse",
    "keyboard": "Keyboard",
    "customer_name": "Customer name",
    "phone_number": "Phone number",
    "email": "Email",
    "comment": "Comment",
    "current_password": "Current password",
    "new_password": "New password",
    "confirm_password": "Confirm password",
    "please_input_new_password": "Please input new password",
    "please_input_confirm_password": "Please input confirm password",
    "please_input_current_password": "Please input current password",
    "password_not_match": "Password not match",
    "first_name": "First name",
    "last_name": "Last name",
    "date_of_birth": "Date of birth",
    "save": "Save",
    "name": "Name",
    "price": "Price",
    "spec": "Spec",
    "khmer": "Khmer",
    "english": "English",
    "chinese": "Chinese",
    "flash_light": "Flashlight",
    "business_partner": "Business Partners",
    "open_qr": "Open QR",
    "scan_qr": "Scan QR",
    "please_place_qr_in_center": "Please place QR in the center",
    "please_enter_place": "Please enter place name",
    "enter_service_code": "Enter service code...",
    "order_info": "Order info",
    "document_number": "Document number",
    "status": "Status",
    "date": "Date",
    "payment": "Payment",
    "subtotal": "Subtotal",
    "shipping_fee": "Shipping fee",
    "total": "Total",
    "filter": "Filter",
    "all_brand": "All Brands",
    "price_range": "Price Range",
    "group": "Group",
    "optional": "Optional",
    "not_select": "Not Selected",
    "passowrd_not_match": "Password not match",
    "create_new_password": "Create new passord",
    "create_password": "Create password",
    "please_input_phone_number": "Please input phone number",
    "please_select_term_and_condition": "Please select terms and condition",
    "please_input_code": "Please input code",
    "failed_no_internet_connection": "Failed to connect to the network",
    "select_language": "Select Language",
    "download": "Download",
    "service_edit": "Service Edit",
    "scan": "Scan",
    "service_tracking": "Service Tracking",
    'change_password_success': "You change password successful.",
    "payment_successfully": "Payment successfully",
    'add_new_place': 'Add new place',
    'apply_change': "Apply change",
    'share_location': "Share location",
    'confirm_payment': "Confirm payment",
    'description_requirement': "Description & Requirement",
    'expired_date': "Expired Date",
    'promotion': "Promotion",
    'product_free': "Product free",
    'product': "Product",
    'free': "Free",
    'Ordering': 'Ordering',
    'Processing': 'Processing',
    'In Delivery': 'In Delivery',
    'Delivery': 'Delivery',
    'max_qty': "Maximum quantity is 1000",
    'storage_permission_not_granted': 'Storage permission not granted',
    'we_cant_access_your_location_at_this_time':
        "We can't access your location at this time. Did you allow location access?",
    'send': "Send",
    'contact_sale': "Contact Sale",
    'contact_delivery': "Contact Delivery",
    'no_messages': 'No messages',
    'job_announcement': 'Job Announcement',
    'add_item_to_cart': 'Add item to cart successfully',
    'permission_denied': 'Permission Denied',
    'camera_assess':
        'We need access to your camera so you can easily take pictures within the app. Would you like to grant camera access now?',
    'user_not_allow_mic':
        'Microphone access was denied. Would you like to open app settings to allow access?',
    'storage_assess':
        'File and media access was denied. Would you like to open app settings to allow access?',
    'open_app_settings': 'Open settings',
    'close': 'Close',
    'location_assess':
        'Location access is required for this feature. Please enable it in settings.',
    'you_have_not_rate_yet': 'You have not rate yet',
    'shipment_address': 'Shipment address',
    'address2': 'Address 2',
    'view_map': 'Edit map',
    'error': 'Something was wrong!',
    'no_item_found': 'Address not found!',
    'confirm': 'Confirm',
    'search_your_location': 'Search your location',
    'send_location': 'Send location',
    'could_not_open_map': 'Could not open Google Maps.',
    'store_location': 'Store location',
    'in_delivery': 'In delivery',
    'Delivered': 'Delivered',
    "image_not_support": "Image not support extention",
    "reason": "Reason",
    "video": "Video"
};

const khmer = {
    "popular_brand": "ម៉ាកល្បីៗ",
    "view_more": "មើលបន្ថែម",
    'view_less': "មើលតិច",
    "categories": "ប្រភេទ",
    "coming_soon": "មកដល់ឆាប់ៗ",
    "search_component": "ស្វែងរកគ្រឿងផ្គុំ",
    "continue": "បន្ត",
    "submit": "ផ្ញើ",
    "cancel": "បោះបង់",
    "ok": "យល់ព្រម",
    "done": "រួចរាល់",
    "remove": "លុប",
    "delete": "លុប",
    "add_to_cart": "ដាក់ចូលកន្ត្រក",
    "discard": "បោះបង់",
    "news": "ព៍ត័មាន",
    "reference": "ការណែនាំ",
    "product_detail": "ព័ត៌មានលម្អិត",
    "buy_now": "ទិញឥឡូវ",
    "tech_specs": "ព័ត៌មានលម្អិតនៃទំនិញ",
    "related_product": "ផលិតផលស្រដៀង",
    "search_product": "ស្វែករកផលិតផល",
    "browse_categories": "រកតាមប្រភេទ",
    "recent_search": "ការស្វែងរកថ្មីៗ",
    "category": "ក្រុមទំនិញ",
    "recommended_for_you": "សម្រាប់អ្នក",
    "search_brand": "ស្វែងរកតាមប្រភេទទំនិញ...",
    "search_categories": "ស្វែងរកក្រុមទំនិញ...",
    "brand": "ប្រេន",
    "search": "ស្វែងរក...",
    "information": "ព័ត៌មាន",
    "faq": "សំណួរ និង ចម្លើយ",
    "loading": "កំពុងផ្ទុក",
    "end_of_records": "អស់ទិន្នន័យ",
    "content": "វីឌីអូ",
    "empty": "មិនមានទិន្នន័យ",
    "no_review": "មិនមានការវាយតម្លៃ",
    "searching": "កំពុងស្វែងរក",
    "please_input_qty": "សូមបញ្ចូលចំនួនទំនិញ",
    "buy_again": "ទិញម្តងទៀត",
    "order_history_info": "ព័ត៌មានអំពីប្រវត្តិនៃការបញ្ជាទិញ",
    "do_you_want_clear_search_history": "តើអ្នកចង់សម្អាតប្រវត្តិស្វែងរកដែរឬទេ",
    "added_to_cart": "បានដាក់ចូលកន្ត្រក",
    "please_select_payment_method": "សូមជ្រើសរើសការទូរទាត់",
    "enter_six_digit_code": "បញ្ចូលលេខកូដ6ខ្ទង់",
    "document_no": "ឯកសារលេខ",
    "phone_no": "លេខទូរសព្ទ",
    "delivery_fee": "ថ្លៃដឹកជញ្ជូន",
    "delivery_info": "ព័ត៌មានអំពីការដឹកជញ្ជូន",
    "order_items_info": "ព័ត៌មាននៃការបញ្ជាទិញ",
    "order_status": "ស្ថានភាពបញ្ជាទិញ",
    "log_to_your_account": "ចូលគណនី",
    "forgot_password": "ភ្លេចពាក្យសម្ងាត់",
    "enter_your_phone_number": "សូមបញ្ចូលលេខទូរស័ព្ទ",
    "already_has_account": "មានគណនីរួចហើយ",
    "register": "ចុះឈ្មោះ",
    "login": "ចូល",
    "sign_up": "ចុះឈ្មោះ",
    "sign_in": "ចូល",
    "do_not_have_account": "តើអ្នកមិនទាន់មានគណនីមែនទេ",
    "password": "ពាក្យសម្ងាត់",
    "enter_validation_code": "សូមបញ្ចូលលេខកូដបញ្ជាក់",
    "do_you_want_to_remove": "តើអ្នកចង់លុប",
    "info": "បញ្ជាក់",
    "processing": "កំពុងដំណើរការ",
    "discount_amount": "បញ្ចុះថ្លៃសរុប",
    "tax": "អាករ",
    "next": "បន្ទាប់",
    "please_select_delivery_method": "សូមជ្រើសរើសវិធីសាស្ត្រដឹកជញ្ជូន",
    "pick_up": "ទទួលផ្ទាល់",
    "check_out": "បញ្ជាទិញ",
    "pay_now": "ទូរទាត់ឥឡូវនេះ",
    "contact_seller": "ទំនាក់ទំនងអាជីវករ",
    "delivery_to": "ដឹកជញ្ជូនទៅ",
    "payment_method": "វិធីសាស្រ្តទូរទាត់ចំណាយ",
    "summary": "សង្ខេប",
    "color": "ព៌ណ",
    "quantity": "ចំនួន",
    "cash": "សាច់ប្រាក់",
    "card": "ប័ណ្ណឥណទាន",
    "tap_to_select_payment": "ចុចដើម្បីជ្រើសរើសការទូរទាត់",
    "select_category": "ជ្រើសរើសក្រុមទំនិញ",
    "select_cpu": "ជ្រើសរើស CPU",
    "select_group": "ជ្រើសរើសក្រុម",
    "select_ram": "ជ្រើសរើស Ram",
    "select_storage": "ជ្រើសរើស Storage",
    "riel": "រៀល",
    "usd": "ដុល្លា",
    "place": "ទីតាំងឈ្មោះ",
    "home_no": "លេខផ្ទះ",
    "street_no": "លេខផ្លូវ",
    "location": "អាស័យដ្ឋាន",
    "request_delivery": "ស្នើរសុំដឹកជញ្ជូន",
    "time": "ពេល",
    "request_service": "ស្នើរសេវ៉ាកម្ម",
    "delivery": "ដឹកជញ្ជូន",
    "request": "ស្នើរសុំ",
    "problem_description": "បរិយាយពីបញ្ហា",
    "problem_image": "រូបភាពបរិយាយបញ្ហា",
    "please_select_image": "សូមជ្រើសរើសរូបភាពបរិយាយបញ្ហា",
    "map_service_not_available": "មិនមានសេវាកម្មផែនទីទេ",
    "type": "ប្រភេទ",
    "request_new_service": "ស្នើរសេវ៉ាកម្មថ្មី",
    "pending": "មិនទាន់បានសម្រេច",
    "edit": "កែប្រែ",
    "result": "លទ្ធផល",
    "checking": "កំពុងពិនិត្យ",
    "problem": "បញ្ហា",
    "complete": "រួចរាល់",
    "get": "ទទួល",
    "review": "មតិយោបល់",
    "how_would_you_like_rate_this_product": "តើអ្នកចង់វាយតម្លៃផលិតផលនេះដោយរបៀបណា",
    "write_your_option": "ការយល់ឃើញរបស់អ្នក",
    "do_you_have_any_photos": "តើអ្នកមានរូបភាពដែរឬទេ?",
    "add_photo": "បញ្ចូលរូប",
    "gallery": "វិចត្រសាល",
    "camera": "កាំមេរ៉ា",
    "processor": "ឧបករណ៍ដំណើរការ",
    "memory": "ការចងចាំ",
    "storage": "ការផ្ទុក",
    "display": "បង្ហាញ",
    "graphic": "ក្រាហ្វិក",
    "os": "OS",
    "code": "កូដ",
    "notification": "សារដំណឹង",
    "shop": "ហាង",
    "chat": "ជជែក",
    "type_your_message": "សរសេរសាររបស់អ្នក",
    "discount": "បញ្ចុះតម្លៃ",
    "home": "ទំព័រដើម",
    "cart": "កន្ត្រក",
    "menu": "ម៉ឺនុយ",
    "build_computer": "រៀបកុំព្យូទ័រ",
    "compare": "ប្រៀបធៀប",
    "wish_list": "បញ្ជីរប្រាថ្នា",
    "blog": "ប្លុក",
    "jobs": "ការងារ",
    "about_us": "អំពីយើង",
    "contact_us": "ទាក់ទងយើង",
    "more": "បន្ថែម",
    "language": "ភាសា",
    "tracking_service": "តាមដានសេវ៉ាកម្ម",
    "order_history": "ប្រវិត្តកម្មង់",
    "corporate": "សាជីវកម្ម",
    "black_list": "បញ្ជីខ្មៅ",
    "e_brochure": "ខិត្តប័ណ្ណអេឡិចត្រូនិច",
    "leasing": "បង់រំលស់",
    "service": "សេវ៉ាកម្ម",
    "networking": "បណ្តាញ",
    "change_password": "ប្តូរពាក្យសម្ងាត់",
    "sign_out": "ចាកចេញ",
    "add_delivery": "បន្ថែមការដឹកជញ្ជូន",
    "address": "អាស័យដ្ឋាន",
    "address_2": "អាស័យដ្ឋាន 2",
    "add_new_address": "បន្ថែមអាស័យដ្ឋាន",
    "please_select_delivery_address": "សូមជ្រើសរើសអាស័យដ្ឋាន",
    "please_enter_your_name": "សូមបញ្ចូលឈ្មោះរបស់អ្នក",
    "please_enter_phone_number": "សូមបញ្ចូលលេខទូរស័ព្ទ",
    "choose_spec_that_you_want": "ជ្រើសរើសគ្រឿងផ្គុំដែលអ្នកចង់បាន",
    "mother_board": "Motherboard",
    "cpu": "CPU",
    "cpu_cooling": "កង្ហារស៊ីភីយូ",
    "ram": "RAM",
    "hard_disk": "Hard Disk",
    "ssd": "SSD",
    "graphic_card": "Graphic card",
    "case": "Case",
    "power_supply": "Power supply",
    "case_fan": "Case fan",
    "monitor": "Monitor",
    "mouse": "Mouse",
    "keyboard": "Keyboard",
    "customer_name": "ឈ្មោះអតិថិជន",
    "phone_number": "លេខទូរស័ព្ទ",
    "email": "អ៊ីម៉ែល",
    "comment": "ខមិន",
    "current_password": "ពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "new_password": "ពាក្យសម្ងាត់ថ្មី",
    "confirm_password": "បញ្ជាក់ពាក្យសម្ងាត់",
    "please_input_new_password": "សូមបញ្ចូលពាក្យសម្ងាត់ថ្មី",
    "please_input_confirm_password": "សូមបញ្ជាក់ពាក្យសម្ងាត់",
    "please_input_current_password": "សូមបញ្ចូលពាក្យសម្ងាត់បច្ចុប្បន្ន",
    "password_not_match": "ពាក្យសម្ងាត់មិនត្រឹមត្រូវ",
    "first_name": "នាមត្រកូល",
    "last_name": "នាមខ្លួន",
    "date_of_birth": "ថ្ងៃខែកំណើត",
    "save": "រក្សាទុក",
    "name": "ឈ្មោះ",
    "price": "តម្លៃ",
    "spec": "លម្អិត",
    "khmer": "ភាសាខ្មែរ",
    "english": "អង់គ្លេស",
    "chinese": "ចិន",
    "flash_light": "ភ្លើង",
    "business_partner": "ដៃគូរសហការ",
    "open_qr": "បើក QR",
    "scan_qr": "ស្កែន QR",
    "please_place_qr_in_center": "សូមដាក់ QR អោយនៅចំកណ្តាល",
    "please_enter_place": "Please enter place name",
    "enter_service_code": "សូមបញ្ចូលលេខកូដសេវ៉ាកម្ម...",
    "order_info": "ព័ត៌មានការកម្មង់",
    "document_number": "លេខកម្មង់",
    "status": "ស្ថានភាព",
    "date": "កាលបរិច្ឆេទ",
    "payment": "ការទូរទាត់",
    "subtotal": "សរុបរង",
    "shipping_fee": "ថ្លៃដឹកជញ្ចូន",
    "total": "សរុប",
    "filter": "តម្រង",
    "all_brand": "ទាំងអស់",
    "price_range": "តារាងតម្លៃ",
    "group": "ក្រុម",
    "not_select": "មិនទាន់ជ្រើសរើស",
    "passowrd_not_match": "លេខសម្ងាត់មិនត្រឹមត្រូវ",
    "create_new_password": "បង្កើតលេខសម្ងាតថ្មី",
    "create_password": "បង្កើតលេខសម្ងាត",
    "please_input_phone_number": "សូមបញ្ចូលលេខទូរស័ព្ទ",
    "please_select_term_and_condition": "សូមជ្រើសរើសលក្ខខណ្ឌ និងការណែនាំ",
    "please_input_code": "សូមបញ្ចូលកូដ",
    "failed_no_internet_connection": "មិនមានតំណរភ្ជាប់",
    "select_language": "ជ្រើសរើសភាសា",
    "are_you_sure_want_to_sign_out": "តើអ្នកប្រាកដជាចង់ចេញ",
    "download": "ទាញយក",
    "service_edit": "សេវាកម្មកែសម្រួល",
    "scan": "ស្កេន",
    "service_tracking": "ការតាមដានសេវាកម្ម",
    "payment_successfully": "ការទូទាត់ទទួលបានជោគជ័យ",
    'change_password_success': "អ្នកផ្លាស់ប្តូរពាក្យសម្ងាត់ជោគជ័យ",
    'add_new_place': 'បន្ថែមកន្លែងថ្មី',
    'apply_change': "អនុវត្តការផ្លាស់ប្តូរ",
    'share_location': "ចែករំលែកទីតាំង",
    'confirm_payment': "បញ្ជាក់ការទូទាត់",
    'description_requirement': "Description & Requirement",
    'expired_date': "កាលបរិច្ឆេទផុតកំណត់",
    'promotion': "Promotion",
    'product_free': "Product free",
    'product': "Product",
    'free': "Free",
    'Ordering': 'ការបញ្ជាទិញ',
    'Processing': 'ដំណើរការ',
    'In Delivery': 'ក្នុងការដឹកជញ្ជូន',
    'Delivery': 'ការដឹកជញ្ជូន',
    'max_qty': "បរិមាណអតិបរមាគឺ 1000",
    'storage_permission_not_granted': 'ការអនុញ្ញាតការផ្ទុកមិនត្រូវបានផ្តល់ឱ្យទេ',
    'we_cant_access_your_location_at_this_time':
        "យើងមិនអាចចូលប្រើទីតាំងរបស់អ្នកបានទេនៅពេលនេះ។ តើអ្នកអនុញ្ញាតឱ្យចូលប្រើទីតាំងទេ?",
    'send': "ផ្ញើ",
    'contact_sale': "ទំនាក់ទំនងទៅផ្នែកលក់",
    'contact_delivery': "ទំនាក់ទំនងទៅអ្នកដឹកជញ្ជូន",
    'no_messages': 'មិនមានសារ',
    'job_announcement': 'ដំណឹងការងារ',
    'add_item_to_cart': 'បន្ថែមទំនិញទៅកន្រកដោយជោគជ័យ',
    'open_app_settings': 'បើកការកំណត់',
    'storage_assess':
        'ឯកសារ និងការចូលប្រើប្រព័ន្ធផ្សព្វផ្សាយត្រូវបានបដិសេធ។ តើអ្នកចង់បើកការកំណត់កម្មវិធីដើម្បីអនុញ្ញាតឱ្យចូលប្រើដែរឬទេ?',
    'user_not_allow_mic':
        'ការចូលប្រើមីក្រូហ្វូនត្រូវបានបដិសេធ។ តើអ្នកចង់បើកការកំណត់កម្មវិធីដើម្បីអនុញ្ញាតឱ្យចូលប្រើដែរឬទេ?',
    'camera_assess':
        'យើងត្រូវការចូលប្រើកាមេរ៉ារបស់អ្នក ដូច្នេះអ្នកអាចថតរូបបានយ៉ាងងាយស្រួលនៅក្នុងកម្មវិធី។ តើអ្នកចង់ផ្តល់សិទ្ធិចូលប្រើកាមេរ៉ាឥឡូវនេះទេ?',
    'permission_denied': 'ការអនុញ្ញាតត្រូវបានបដិសេធ',
    'close': 'Close',
    'location_assess':
        'ការចូលប្រើទីតាំងត្រូវបានទាមទារសម្រាប់មុខងារនេះ សូមបើកវានៅក្នុងការកំណត់',
    'you_have_not_rate_yet': 'អ្នកមិនទាន់វាយតម្លៃនៅឡើយទេ',
    'shipment_address': 'អាសយដ្ឋានដឹកជញ្ជូន',
    'address2': 'អាសយដ្ឋាន 2',
    'view_map': 'កែផែនទី',
    'error': 'មានអ្វីមួយខុស!',
    'no_item_found': 'រកមិនឃើញអាសយដ្ឋាន!',
    'confirm': 'បញ្ជាក់',
    'search_your_location': 'ស្វែងរកទីតាំងរបស់អ្នក',
    'send_location': 'ផ្ញើទីតាំង',
    'could_not_open_map': 'មិនអាចបើក Google Maps បានទេ',
    'store_location': 'ទីតាំងហាង',
    'in_delivery': 'ក្នុងការដឹកជញ្ជូន',
    'Delivered': 'ត្រូវបានដឹក',
    "image_not_support": "រូបភាពមិនគាំទ្រ",
    "reason": "មូលហេតុ",
    "video": "វីដេអូ",
    "please_enter_address": "សូមបញ្ចូលអាសយដ្ឋាន",
    "phone": "ទូរស័ព្ទ",
    "do_you_want_to_delete": "តើអ្នកចង់លុបទេ",
    "signing_out": "ចេញ",
    "update": "ធ្វើបច្ចុប្បន្នភាព",
    "create": "បង្កើត",
    "not_available": "មិនអាចប្រើបានទេ",
    "not_receive_code": "មិនទទួលលេខកូដ",
    "resend": "ផ្ញើឡើងវិញ",
    "create_account": "បង្កើតគណនី",
    "agree_term_and_service": "តាមរយៈការចុះឈ្មោះ អ្នកយល់ព្រមតាមលក្ខខណ្ឌរបស់យើង",
    "please_enter_6_digit_code": "សូមបញ្ចូលលេខកូដ 6 ខ្ទង់",
    "please_enter_first_name": "សូមបញ្ចូលឈ្មោះដំបូង",
    "please_enter_last_name": "សូមបញ្ចូលនាមត្រកូល",
    "please_enter_password": "សូមបញ្ចូលពាក្យសម្ងាត់",
    "please_enter_confirm_password": "សូមបញ្ចូលការបញ្ជាក់ពាក្យសម្ងាត់",
    "please_check_term_and_condition": "សូមពិនិត្យមើលលក្ខខណ្ឌ",
    "optional": "ស្រេចចិត្ត"
};




async function createExcel() {
    const workbook = new ExcelJS.Workbook();

    // Create English sheet
    const worksheetEnglish = workbook.addWorksheet('English Localization');
    worksheetEnglish.addRow(['Key', 'Translation']);
    for (const [key, value] of Object.entries(english)) {
        worksheetEnglish.addRow([key, value]);
    }

    // Create Khmer sheet
    const worksheetKhmer = workbook.addWorksheet('Khmer Localization');
    worksheetKhmer.addRow(['Key', 'Translation']);
    for (const [key, value] of Object.entries(khmer)) {
        worksheetKhmer.addRow([key, value]);
    }

    // Create Khmer sheet
    const worksheetChaina = workbook.addWorksheet('Chaina Localization');
    worksheetChaina.addRow(['Key', 'Translation']);
    for (const [key, value] of Object.entries(english)) {
        worksheetChaina.addRow([key, value]);
    }

    // // Compare keys and create Missing Keys sheet
    // const worksheetMissingKeys = workbook.addWorksheet('Missing Keys');
    // worksheetMissingKeys.addRow(['Key', 'Missing in Khmer?', 'Missing in English?']);


    // // Find missing keys in Khmer
    // const englishKeys = Object.keys(english);
    // const khmerKeys = Object.keys(khmer);


    // for (const key of englishKeys) {
    //     const missingInKhmer = khmerKeys.includes(key) ? 'No' : 'Yes';
    //     const missingInEnglish = englishKeys.includes(key) ? 'No' : 'Yes';
    //     worksheetMissingKeys.addRow([key, missingInKhmer, missingInEnglish]);
    // }

    // Save the Excel file
    await workbook.xlsx.writeFile('psc_localization.xlsx');
    console.log("Excel file created!");
}

createExcel().catch(console.error);